import stuff (a lot of stuff) & read in data

In [7]:
import pandas as pd
import numpy as np
import category_encoders as ce
import datetime as dt
pd.options.mode.chained_assignment = None
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
pd.options.display.max_rows = 1000
pd.options.display.max_columns= 1000
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn import metrics
import scipy.stats as stats
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [8]:
data = pd.read_csv('../datasets/ks-projects-201801.csv')

In [9]:
data.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

# data cleaning / transforming

create a new column denoting length of project name (number of characters)

In [10]:
data['titleLength'] = data['name'].apply(lambda x: len(str(x)))

drop columns that won't be used at the moment (main_category, ID, name, state, pledged, usd pledged, goal)

In [11]:
data.drop(columns=['main_category','ID','name','state','pledged','usd pledged','goal'],inplace=True)

format date columns properly and get rid of records with invalid dates (precede the year 2000)

In [12]:
data['launched'] = pd.to_datetime(data['launched'])
data['deadline'] = pd.to_datetime(data['deadline'])
df = data[data['launched']>'2000-01-01']

eliminate projects with usd pledged real > 20000 or usd pledged real = 0

TODO: write a brief explanation as to why you are doing this (double-click on this cell to edit the text)

In [13]:
df = data[(data['usd_pledged_real']<20000) & (data['usd_pledged_real']>0)]

create logged versions of usd pledged real and usd goal real + drop the original nonlogged versions

TODO: write a brief explanation as to why you are doing this

In [14]:
df['logPledged'] = np.log(df['usd_pledged_real'])
df['logGoal'] = np.log(df['usd_goal_real'])

df.drop(columns=['usd_goal_real','usd_pledged_real'], inplace=True)

create columns to encode the 'launched' column -- I chose to break it down into month, day of week, and hour

In [15]:
df['launchMonth'] = df['launched'].dt.month
df['launchDay'] = df['launched'].dt.dayofweek
df['launchHour'] = df['launched'].dt.hour

calculate the duration of each project campaign + drop the launched & deadline columns

In [16]:
df['duration'] = (df['deadline']-df['launched'])/dt.timedelta(minutes=1)
df.drop(columns=['deadline','launched'],inplace=True)

# model preparation

divide dataset into features (X) and target (y)

In [17]:
X = df.drop(columns=['logPledged'])
y = df['logPledged']

prepare the pipeline (for help, see bottom of this article https://kiwidamien.github.io/encoding-categorical-variables.html)

In [18]:
#some helper code for you
import joblib
location = 'cache'
memory = joblib.Memory(location=location, verbose=10)

encoding_pipeline = Pipeline([
    ('encode_category', ce.HashingEncoder(cols=['category'], return_df=True)),
    ('encode_other', ce.OneHotEncoder(cols=['currency','country','launchMonth','launchDay','launchHour'], return_df=True)),
], memory=memory)

train-test-split your data

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

encode your training set and test set (for reference, see documentation here https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html)

TODO: explain when to use fit_transform( ) vs transform( ) and why

In [20]:
X_train_encoded = encoding_pipeline.fit_transform(X_train, y_train)
X_test_encoded = encoding_pipeline.transform(X_test)

________________________________________________________________________________
[Memory] Calling sklearn.pipeline._fit_transform_one...
_fit_transform_one(HashingEncoder(cols=['category'], drop_invariant=False, hash_method='md5',
               max_process=2, max_sample=0, n_components=8, return_df=True,
               verbose=0),
              category currency  backers country  titleLength    logGoal  \
132449    Performances      USD       39      US           55   8.517193
80239      Documentary      USD       89      US           37   8.699515
281941  Product Design      USD        5      US           42  11.225243
254197            Food      USD        9      US           17   8.517193
303507  Tabletop Games      USD        8      US           15   9.510445
...                ...      ...      ...     ...          ...        ...
22070           Drinks      USD       23      US           22   8.699515
313017  Product Design      USD       29      US           53   8.517193
188706          ...,
132449    8.537192
80239     8.777247
281941    6.946976
254197    6.291569
303507    5.934894
            ...
22070     7.673223
313017    8.541886
188706    8.080856
265154    2.068128
263606    4.488636
Name: logPledged, Length: 239189, dtype: float64,
None, message_clsname='Pipeline', message=None)

/Users/Jesse/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py:317: UserWarning: Persisting input arguments took 3.58s to run.
If this happens often in your code, it can cause performance problems
(results will be correct in all cases).
The reason for this is probably some large input arguments for a wrapped
 function (e.g. large strings).
THIS IS A JOBLIB ISSUE. If you can, kindly provide the joblib's team with an
 example so that they can fix the problem.
  **fit_params_steps[name])

______________________________________________fit_transform_one - 195.2s, 3.3min

check to make sure that the dimensions align between test & training

In [21]:
print(X_train_encoded.shape)
print(X_test_encoded.shape)

(239189, 92)
(59798, 92)

In [22]:
X_test_encoded.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,currency_1,currency_2,currency_3,currency_4,currency_5,currency_6,currency_7,currency_8,currency_9,currency_10,currency_11,currency_12,currency_13,currency_14,backers,country_1,country_2,country_3,country_4,country_5,country_6,country_7,country_8,country_9,country_10,country_11,country_12,country_13,country_14,country_15,country_16,country_17,country_18,country_19,country_20,country_21,country_22,country_23,titleLength,logGoal,launchMonth_1,launchMonth_2,launchMonth_3,launchMonth_4,launchMonth_5,launchMonth_6,launchMonth_7,launchMonth_8,launchMonth_9,launchMonth_10,launchMonth_11,launchMonth_12,launchDay_1,launchDay_2,launchDay_3,launchDay_4,launchDay_5,launchDay_6,launchDay_7,launchHour_1,launchHour_2,launchHour_3,launchHour_4,launchHour_5,launchHour_6,launchHour_7,launchHour_8,launchHour_9,launchHour_10,launchHour_11,launchHour_12,launchHour_13,launchHour_14,launchHour_15,launchHour_16,launchHour_17,launchHour_18,launchHour_19,launchHour_20,launchHour_21,launchHour_22,launchHour_23,launchHour_24,duration
0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,150,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,54,9.602382,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,42102.716667
1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,9.740969,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,63591.333333
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,21,8.231940,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,77768.266667
3,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,104,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,7.718685,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,43160.533333
4,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,33,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,42,8.987197,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,41817.366667

# linear regression

create & fit linear regression model on training set

In [33]:
linreg = LinearRegression()
linreg.fit(X_train_encoded,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

calculate & output MAE, MSE, RMSE based on test set AND interpret them in the context of this project

In [34]:
mae = metrics.mean_absolute_error(y_test,linreg.predict(X_test_encoded))
mse = metrics.mean_squared_error(y_test,linreg.predict(X_test_encoded))
rmse = np.sqrt(metrics.mean_squared_error(y_test,linreg.predict(X_test_encoded)))
r2 = metrics.r2_score(y_test, linreg.predict(X_test_encoded))

In [35]:
print("mae: ", mae)
print("mse: ", mse)
print("rmse: ", rmse)
print("r2: ", r2)

mae:  1.5432393024437199
mse:  3.892822526894883
rmse:  1.9730237015542624
r2:  0.32942781866418036

In [43]:
list(zip(X_train_encoded.columns, linreg.coef_))

[('col_0', 0.04558383950316178),
 ('col_1', -0.272015088120959),
 ('col_2', -0.24427716623720866),
 ('col_3', 0.0684485708659164),
 ('col_4', 0.2859418654124542),
 ('col_5', 0.1864497153756942),
 ('col_6', -0.09470994122875936),
 ('col_7', 0.02457820442885715),
 ('currency_1', 0.7626665189567149),
 ('currency_2', 4.326245774899373e-05),
 ('currency_3', -1.0603899457945862),
 ('currency_4', 0.5423838903692689),
 ('currency_5', -0.6183348903086006),
 ('currency_6', 0.48007248157555393),
 ('currency_7', -0.12422721139216601),
 ('currency_8', -0.36364437430914864),
 ('currency_9', 0.5164070678890118),
 ('currency_10', 0.08125595692414966),
 ('currency_11', 0.48877468831143844),
 ('currency_12', -0.6664143089922602),
 ('currency_13', -0.03970782136788448),
 ('currency_14', 0.0011146856812512262),
 ('backers', 0.016954072548968094),
 ('country_1', -0.769631162896362),
 ('country_2', -0.39506341862481986),
 ('country_3', 0.29785834889189333),
 ('country_4', -0.706418437106037),
 ('country_5', 0.44301473744390374),
 ('country_6', 0.26549263360850617),
 ('country_7', 0.3924206035368342),
 ('country_8', -1.0714012265717083),
 ('country_9', -0.12422721139220859),
 ('country_10', -0.3636443743090598),
 ('country_11', 0.8623037261552338),
 ('country_12', -0.9287779120696729),
 ('country_13', 0.08125595692411924),
 ('country_14', 0.03111917707170489),
 ('country_15', -0.8113413069486316),
 ('country_16', 0.42552681190296165),
 ('country_17', 0.599454726079324),
 ('country_18', -0.6531842725600792),
 ('country_19', 0.3770915248777107),
 ('country_20', 0.7303090595877346),
 ('country_21', 0.36863743496406975),
 ('country_22', 0.9480898957525898),
 ('country_23', 0.0011146856812398603),
 ('titleLength', 0.013830736789383291),
 ('logGoal', 0.07926310820065485),
 ('launchMonth_1', -0.06551176775338921),
 ('launchMonth_2', 0.0077506490688615814),
 ('launchMonth_3', 0.16641823472881123),
 ('launchMonth_4', -0.2145301565831763),
 ('launchMonth_5', 0.04683549432784903),
 ('launchMonth_6', -0.09168929254610902),
 ('launchMonth_7', 0.09386620169980261),
 ('launchMonth_8', 0.09339884523812868),
 ('launchMonth_9', 0.10196588195191432),
 ('launchMonth_10', -0.17760279798652434),
 ('launchMonth_11', 0.08732258915246982),
 ('launchMonth_12', -0.04822388129892925),
 ('launchDay_1', -0.005008893226963185),
 ('launchDay_2', -0.019274239875329724),
 ('launchDay_3', 0.0290192319345704),
 ('launchDay_4', -0.0034288476588217875),
 ('launchDay_5', 0.007472906867138807),
 ('launchDay_6', -0.03783428126721422),
 ('launchDay_7', 0.02905412322654788),
 ('launchHour_1', -0.05717532357497017),
 ('launchHour_2', -0.12795103859603557),
 ('launchHour_3', 0.23118263780868392),
 ('launchHour_4', -0.027672475065077112),
 ('launchHour_5', 0.02930171076497698),
 ('launchHour_6', -0.14858164031360438),
 ('launchHour_7', 0.12294884823162681),
 ('launchHour_8', -0.14697150681585447),
 ('launchHour_9', -0.07711940418135209),
 ('launchHour_10', 0.006463743870476407),
 ('launchHour_11', -0.12811975891021327),
 ('launchHour_12', -0.03956515674816516),
 ('launchHour_13', 0.07276864662640009),
 ('launchHour_14', -0.15474946075577292),
 ('launchHour_15', 0.15826600752224715),
 ('launchHour_16', 0.18189117477381433),
 ('launchHour_17', -0.06396452750099886),
 ('launchHour_18', -0.0743237143289307),
 ('launchHour_19', -0.10597715478708564),
 ('launchHour_20', 0.03539234208118891),
 ('launchHour_21', 0.04244962107157954),
 ('launchHour_22', 0.1692853303119375),
 ('launchHour_23', -0.054625359707221585),
 ('launchHour_24', 0.15684645822216653),
 ('duration', -4.2864225635042e-06)]

# DTR / RF
I'm assuming you get the hang of things by now -- just repeat the process

*don't worry about using GridSearch at the moment

In [36]:
dtr = DecisionTreeRegressor()
dtr.fit(X_train_encoded,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [37]:
mae = metrics.mean_absolute_error(y_test,dtr.predict(X_test_encoded))
mse = metrics.mean_squared_error(y_test,dtr.predict(X_test_encoded))
rmse = np.sqrt(metrics.mean_squared_error(y_test,dtr.predict(X_test_encoded)))
r2 = metrics.r2_score(y_test, dtr.predict(X_test_encoded))

In [38]:
print("mae: ", mae)
print("mse: ", mse)
print("rmse: ", rmse)
print("r2: ", r2)

mae:  0.9389532433958205
mse:  1.9707283450846926
rmse:  1.4038263229775585
r2:  0.6605250827507203

In [39]:
rfr = RandomForestRegressor()
rfr.fit(X_train_encoded,y_train)

/Users/Jesse/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [40]:
mae = metrics.mean_absolute_error(y_test,rfr.predict(X_test_encoded))
mse = metrics.mean_squared_error(y_test,rfr.predict(X_test_encoded))
rmse = np.sqrt(metrics.mean_squared_error(y_test,rfr.predict(X_test_encoded)))
r2 = metrics.r2_score(y_test, rfr.predict(X_test_encoded))

In [41]:
print("mae: ", mae)
print("mse: ", mse)
print("rmse: ", rmse)
print("r2: ", r2)

mae:  0.710467817728967
mse:  1.0928443407674713
rmse:  1.0453919555685662
r2:  0.8117481574395088

In [42]:
# compute feature importances
pd.DataFrame({'feature':X_test_encoded.columns, 
              'importance':rfr.feature_importances_}).sort_values(by='importance',ascending=False)

           feature  importance
22         backers    0.790210
47         logGoal    0.044444
91        duration    0.031752
28       country_6    0.023247
46     titleLength    0.021389
60     launchDay_1    0.002545
64     launchDay_5    0.002406
61     launchDay_2    0.002349
63     launchDay_4    0.002332
62     launchDay_3    0.002291
7            col_7    0.002211
0            col_0    0.002173
3            col_3    0.001940
4            col_4    0.001919
65     launchDay_6    0.001827
1            col_1    0.001826
57  launchMonth_10    0.001755
52   launchMonth_5    0.001721
89   launchHour_23    0.001707
68    launchHour_2    0.001664
83   launchHour_17    0.001656
74    launchHour_8    0.001647
59  launchMonth_12    0.001643
70    launchHour_4    0.001641
53   launchMonth_6    0.001640
56   launchMonth_9    0.001637
2            col_2    0.001626
49   launchMonth_2    0.001624
72    launchHour_6    0.001599
6            col_6    0.001582
50   launchMonth_3    0.001573
48   launchMonth_1    0.001546
55   launchMonth_8    0.001542
80   launchHour_14    0.001522
54   launchMonth_7    0.001512
51   launchMonth_4    0.001503
66     launchDay_7    0.001459
58  launchMonth_11    0.001459
85   launchHour_19    0.001371
77   launchHour_11    0.001362
5            col_5    0.001334
75    launchHour_9    0.001322
79   launchHour_13    0.001307
84   launchHour_18    0.001274
8       currency_1    0.001225
78   launchHour_12    0.001212
82   launchHour_16    0.001201
67    launchHour_1    0.001134
86   launchHour_20    0.001017
69    launchHour_3    0.000964
23       country_1    0.000960
10      currency_3    0.000943
76   launchHour_10    0.000901
11      currency_4    0.000850
81   launchHour_15    0.000783
71    launchHour_5    0.000730
90   launchHour_24    0.000722
26       country_4    0.000712
9       currency_2    0.000691
87   launchHour_21    0.000673
73    launchHour_7    0.000655
88   launchHour_22    0.000586
24       country_2    0.000585
25       country_3    0.000504
13      currency_6    0.000495
27       country_5    0.000471
30       country_8    0.000450
39      country_17    0.000426
33      country_11    0.000354
29       country_7    0.000339
12      currency_5    0.000248
32      country_10    0.000219
15      currency_8    0.000196
36      country_14    0.000183
16      currency_9    0.000159
37      country_15    0.000147
34      country_12    0.000128
41      country_19    0.000122
20     currency_13    0.000114
18     currency_11    0.000110
19     currency_12    0.000100
42      country_20    0.000097
40      country_18    0.000094
43      country_21    0.000086
38      country_16    0.000082
35      country_13    0.000076
17     currency_10    0.000063
14      currency_7    0.000045
31       country_9    0.000037
44      country_22    0.000011
21     currency_14    0.000005
45      country_23    0.000003

# using gridsearch with pipelines,  creating a custom scaler

In [45]:
#no need to TTS when using GridSearch
X = df.drop(columns=['logPledged'])
y = df['logPledged']

In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [48]:
df.describe()

,backers,titleLength,logPledged,logGoal,launchMonth,launchDay,launchHour,duration
count,298987.000000,298987.000000,298987.000000,298987.000000,298987.000000,298987.000000,298987.000000,298987.000000
mean,42.005783,34.963704,6.264790,8.492713,6.437173,2.449829,13.029215,48232.831613
std,73.313672,15.900229,2.408320,1.626035,3.340454,1.771127,7.753882,18440.349669
min,0.000000,1.000000,-0.798508,-4.605170,1.000000,0.000000,0.000000,7.283333
25%,3.000000,22.000000,4.700480,7.600902,4.000000,1.000000,5.000000,41887.525000
50%,15.000000,34.000000,6.729824,8.517193,6.000000,2.000000,16.000000,42737.600000
75%,50.000000,49.000000,8.168608,9.431401,9.000000,4.000000,20.000000,52079.625000
max,4015.000000,96.000000,9.903487,18.517533,12.000000,6.000000,23.000000,132426.216667

## Standard Scaler
- standardize features by removing the mean and scaling to unit variance
- calculated as: z = (x - u) / s
- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

### Implementation

In [ ]:
scaler = StandardScaler()
scaler.fit(df)

- as you can see, the basic implementation doesn't really work here since it can only apply the scaler to the entire dataset, which contains categorical columns
- thus, we are going to wrap it into a function that allows us to apply the scaler to specific functions

### ColumnTransformer
- applies transformers to columns of an array or dataframe
- allows different columns to be transformed separately, which is useful for heterogeneous data

In [ ]:
#why we need to wrap this into a function
scaler = ColumnTransformer([
            ('standardize', StandardScaler(), ['duration','titleLength'])
        ])

scaler.fit_transform(X,y)

- you can think of 'standardize' as a step that applies StandardScaler() to the duration and titleLength columns
- unfortunately, this returns a single array corresponding to the newly-scaled columns, but we want it to result in an entire dataframe containing the newly-scaled columns
- why is this? check out the output of running each step in your original pipeline -- they're all dataframes, so we want to keep things consistent
- thus, we are going to wrap everything into yet another function

In [3]:
def scaling(X,y):
    scaler = ColumnTransformer([
            ('standardize', StandardScaler(), ['duration','titleLength'])
        ])
    X[['duration','titleLength']] = scaler.fit_transform(X,y)

in this function, we...
- pass in the feature and target dataframes
- create a "scaler" object as described earlier
- fit the scaler & transform the data to get the newly-scaled columns (in the form of an array) and then replace the original unscaled columns

## Pipeline
- the first two steps are the same as before
- we've added the additional step 'scale' that runs the scaling function we defined above
- in order to run gridsearch, we also need another step that refers to the model
- in this case, the step is called 'forest', and it runs the random forest regressor defined earlier

In [ ]:
pipeline = Pipeline([
    ('hash', ce.HashingEncoder(cols=['category'])),
    ('onehot', ce.OneHotEncoder(cols=['currency','country','launchMonth','launchDay','launchHour'])),
    ('scale', scaling(X,y)),
    ('forest', rfr)
], memory=memory)

## GridSearch
- as you may know, gridsearch allows you to try different values and combinations of parameters
- thus, we need to create a grid of paramters to test (in the form of a dictionary)
- the syntax of each dictionary entry is 'pipelineModelStepName__parameterName' : [values to test]
- you can find the list of possible parameterNames in the documentation for DT/RF

In [ ]:
parameters = {'forest__max_depth':[10,20],
              'forest__min_samples_leaf':[25,50]}

In [ ]:
gs = GridSearchCV(pipeline,parameters)

gs.fit(X_train,y_train)

scores = pd.DataFrame(gs.cv_results_).filter(regex='param_+|mean_test_score'
                                            ).sort_values('mean_test_score',
                                                          ascending=False).reset_index().drop(['index'],axis=1)
scores.head(20)